export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const FETCH_USERS_START = 'FETCH_USERS';
export const FETCH_USERS= 'FETCH_USERS';