export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS = 'FETCH_USERS';
export const CREATE_USER = 'CREATE_USERS';
export const CREATE_USER_START = 'CREATE_USERS_START';
export const CREATE_USER_ERROR = 'CREATE_USERS_ERROR';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const LOCAL_SAVE_USER = 'LOCAL_SAVE_USER';

export const FETCH_SUCCESS_EVENTS = 'FETCH_SUCCESS_EVENTS';
export const FETCH_SUCCESS_USERS = 'FETCH_SUCCESS_USERS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_START = 'FETCH_START';
export const FETCH = 'FETCH';

export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_ERROR = 'CREATE_ERROR';
export const CREATE_START = 'CREATE_START';
export const CREATE = 'CREATE';
export const LOCAL_SAVE = 'LOCAL_SAVE';

export const SET_MESSAGE = "SET_MESSAGE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const FETCH_ORG_SUCCESS = "FETCH_ORG_SUCCESS";
export const FETCH_ORG_ERROR = "FETCH_ORG_ERROR";
export const FETCH_ORG_START = "FETCH_ORG_START";
export const FETCH_ORG = "FETCH_ORG";
export const SHOW_ORG_MODAL = "SHOW_ORG_MODAL";

export const CREATE_ORG_SUCCESS = "CREATE_ORG_SUCCESS";
export const CREATE_ORG_ERROR = "CREATE_ORG_ERROR";
export const CREATE_ORG_START = "CREATE_ORG_START";
export const CREATE_ORG = "CREATE_ORG";
